---
title: I Generated a Sample Survey Product
author: Matthew Pawliw-Levac
date: '2020-10-04'
slug: i-generated-a-sample-survey-product
categories:
  - I Generated
  - R
tags:
  - dashboard
  - shiny
  - github
  - buttons
---

This is a thing I made:  
https://mpawliw-levac.shinyapps.io/learning_styles_sample/

<iframe width="600" height="700" frameborder="no" src="https://mpawliw-levac.shinyapps.io/learning_styles_sample/"> </iframe>

**Why did I make it?**  
This app was made based on a survey that a [teacher collaborator](https://pmdrnikki.wordpress.com/) distributed to students to learn more about them. This app expands on the [Potionmaster app](https://mpawliw-levac.shinyapps.io/potionmaster/), trying to add more features and make the product nicer looking.

**What did I make?**  
In total, this process takes in responses from a [public google form](https://forms.gle/LspRNTpB3L7agDLWA), with the outputted sheet being directly used by this app. This app currently only deals with the quantitative responses from the data. Users are able to select demographics from collapsible check lists with a value box showing the number of students currently selected. The explorable data is split into 3 tabs based on content

**Why I Think It's Cool?**  
	• The collapsible checklists are really handy and prevent a person from getting lost in the number of options available for selecting.  
	• There are a large number of districts in Taiwan (where the survey was based) and I was able to ensure that the checklist only included districts that respondents lived in (the other categories I already knew to use the Forcats package for).  
	• This process takes care of everything from the survey to the results automatically.

**Limitations or Problems**  
	• A report is likely a much better format for this sort of data than an interactive app.  
	• I think I prefer tabset panels to using shiny dashboard's menu items for this sort of product where the sidebar is being used for granularity.  
	• 'mean ranking of intelligences' plot can be hard to understand.  
	• Didn't bother to include qualitative results.  
[Raw code available here](https://github.com/mpawliwllevac/R-Scripts-Reference/tree/master/Sample%20Survey%20Product%20(Learning%20Styles%20Sample))  
[Survey available here](https://forms.gle/LspRNTpB3L7agDLWA)