---
title: 'Down the Rabbit Hole: Data Equity'
author: Matthew Pawliw-Levac
date: '2023-10-18'
categories:
  - R
  - Down the Rabbit Hole
tags:
  - blogdown
  - Book
  - Review
---


 Today's rabbit hole is data equity. A word that encapsulates a lot of what I feel like I've wanted to learn about for a long time now. This is really only the start so will essentially be a summary of a cool article I found as well as a log of further reading on the topic. The article is amazing and should be read. There's even a video version!

Unfair Comparisons: How Visualizing Social Inequality Can Make It Worse TLDR:  

* Deficit framing is a bias that people who suffer from inequalities are somehow to blame for them. Deficit thinking is harmful because it encourages things like victim blaming or believing that it’s a characteristic of the group itself that's causing the differences. This overlaps with ideas around stereotypes. 
* People don't tend to think about variance (different from uncertainty) when looking at visualizations like bar charts and that's not helped by the chart only showing a single number for each group.
* The design of charts matters, charts that better visualize variability tend to work much better for this so that its harder or impossible to ignore.
* Confidence intervals are specifically not included in the "visualizing variability" group since it shows the uncertainty instead of the actual variability. Confidence intervals can even help to reinforce stereotypes
* Using a single number (eg mean) to represent a group is maybe a bad idea. 

Connections:  

* At a different level is how things like algorithms can unintentionally reinforce things like stereotypes or systemic racism so this isn't just happening at a data vis level (link to review, link to book)

Further Reading: 

* [The actual research project, Dispersion vs Disparity: Hiding Variability Can Encourage Stereotyping When Visualizing Social Outcomes](https://arxiv.org/abs/2208.04440), by Eli Holder, Cindy Xiong
* [The Do No Harm Guide](https://www.urban.org/research/publication/do-no-harm-guide-applying-equity-awareness-data-visualization), by Jon Schwabish and Alice Feng which interviewed many experts on a numnber of different considerations.
* [Algorithms of Oppression](https://nyupress.org/9781479837243/algorithms-of-oppression/), by Safiya Umoja Noble helps to illustrate the systemic ways discrimination is being fostered online
* [Principles of Social Psychology – 1st International H5P Edition](https://opentextbc.ca/socialpsychology/) by Dr. Rajiv Jhangiani and Dr. Hammond Tarry is just a generally useful and free social psychology textbook
* [What can go wrong? Exploring racial equity dataviz and deficit thinking](https://3iap.com/what-can-go-wrong-racial-equity-data-visualization-deficit-thinking-VV8acXLQQnWvvg4NLP9LTA/), with Pieta Blakely talks more about the impacts of deficit thinking
* [The trap of false simplicity](https://nightingaledvs.com/when-oversimplification-obscures/) by Ama Nyame-Mensah
* [More from Nightingale](https://nightingaledvs.com/) who were the ones who started me down this path.
